import { defineConfig, loadEnv } from 'vite'
import react from '@vitejs/plugin-react'
import tailwindcss from '@tailwindcss/vite'

/**
 * Emits the Apache/LiteSpeed config that Hostinger needs alongside the build.
 *
 * Generating it here rather than committing a static file keeps the CSP's
 * `connect-src` in lockstep with VITE_API_URL — a mismatch between the two
 * silently blocks every API call in the browser.
 */
function htaccessPlugin(env) {
  const apiOrigin = (() => {
    try {
      return new URL(env.VITE_API_URL).origin
    } catch {
      return ''
    }
  })()

  const connectSrc = ["'self'", apiOrigin].filter(Boolean).join(' ')

  return {
    name: 'emit-htaccess',
    apply: 'build',
    generateBundle() {
      this.emitFile({
        type: 'asset',
        fileName: '.htaccess',
        source: `# Generated by vite build — do not edit by hand.
# API origin baked in from VITE_API_URL: ${apiOrigin || '(not set)'}

# ── Single-page app routing ───────────────────────────────────
# Without this, refreshing /school-panel asks Apache for a file that does not
# exist and returns 404 instead of loading the app.
<IfModule mod_rewrite.c>
  RewriteEngine On
  RewriteBase /

  # Force HTTPS.
  RewriteCond %{HTTPS} !=on
  RewriteCond %{HTTP:X-Forwarded-Proto} !https
  RewriteRule ^(.*)$ https://%{HTTP_HOST}/$1 [R=301,L]

  # Serve real files and directories as-is.
  RewriteCond %{REQUEST_FILENAME} -f [OR]
  RewriteCond %{REQUEST_FILENAME} -d
  RewriteRule ^ - [L]

  # Everything else is handled by the client-side router.
  RewriteRule . /index.html [L]
</IfModule>

# ── Security headers ──────────────────────────────────────────
<IfModule mod_headers.c>
  Header always set Content-Security-Policy "default-src 'self'; script-src 'self'; style-src 'self' 'unsafe-inline' https://fonts.googleapis.com; font-src 'self' https://fonts.gstatic.com data:; img-src 'self' data: blob: https://res.cloudinary.com; connect-src ${connectSrc}; frame-src 'self' https://www.google.com; frame-ancestors 'none'; base-uri 'self'; form-action 'self'; object-src 'none'"
  Header always set X-Content-Type-Options "nosniff"
  Header always set Referrer-Policy "strict-origin-when-cross-origin"
  Header always set Permissions-Policy "geolocation=(), microphone=(), camera=(), interest-cohort=()"
  Header always set Strict-Transport-Security "max-age=31536000; includeSubDomains"
  Header always set X-Frame-Options "DENY"
</IfModule>

# ── Caching ───────────────────────────────────────────────────
<IfModule mod_headers.c>
  # Hashed filenames change on every build, so they can be cached forever.
  <FilesMatch "\\.(js|css|woff2?|ttf|eot|otf)$">
    Header set Cache-Control "public, max-age=31536000, immutable"
  </FilesMatch>

  <FilesMatch "\\.(png|jpe?g|gif|svg|webp|avif|ico)$">
    Header set Cache-Control "public, max-age=2592000"
  </FilesMatch>

  # index.html must always be revalidated, otherwise a cached copy keeps
  # pointing browsers at asset filenames from the previous deploy.
  <FilesMatch "^(index\\.html|sitemap\\.xml|robots\\.txt)$">
    Header set Cache-Control "no-cache, must-revalidate"
  </FilesMatch>
</IfModule>

# ── Compression ───────────────────────────────────────────────
<IfModule mod_deflate.c>
  AddOutputFilterByType DEFLATE text/html text/plain text/css text/xml
  AddOutputFilterByType DEFLATE application/javascript application/json
  AddOutputFilterByType DEFLATE application/xml image/svg+xml
</IfModule>

# ── Misc ──────────────────────────────────────────────────────
DirectoryIndex index.html
Options -Indexes
ErrorDocument 404 /index.html

<IfModule mod_mime.c>
  AddType application/javascript .js .mjs
  AddType image/svg+xml .svg
  AddType font/woff2 .woff2
</IfModule>
`,
      })
    },
  }
}

// https://vite.dev/config/
export default defineConfig(({ mode }) => {
  const env = loadEnv(mode, process.cwd(), 'VITE_')

  return {
    plugins: [react(), tailwindcss(), htaccessPlugin(env)],
    build: {
      // Surfaces oversized chunks in CI rather than after a slow page load.
      chunkSizeWarningLimit: 600,
      rollupOptions: {
        output: {
          manualChunks(id) {
            if (!id.includes('node_modules')) return
            if (id.includes('react-router')) return 'router'
            if (id.includes('/react/') || id.includes('react-dom')) return 'react'
            if (id.includes('xlsx') || id.includes('papaparse')) return 'sheets'
            if (id.includes('lucide-react')) return 'icons'
          },
        },
      },
    },
  }
})
